DROP TABLE IF EXISTS maps CASCADE;
DROP TABLE IF EXISTS map_contributors CASCADE;
DROP TABLE IF EXISTS map_icons CASCADE;

CREATE TABLE map_icons (
  id SERIAL PRIMARY KEY NOT NULL,
  icon VARCHAR(255),
  name VARCHAR(255)
);
